# Generated by Django 4.2.5 on 2023-09-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
